-- TR recovery for initial import db
-- not optmized

-- Disable fk constraint
	ALTER TABLE JUNCTION_POINT 			DISABLE constraint JUNCTION_POINT_FK1;
	ALTER TABLE NODE_POINT 				DISABLE constraint FK_NP_ROADWAY_POINT_ID;
	ALTER TABLE CALIBRATION_POINT 		DISABLE constraint CP_ROADWAY_POINT_FK;
	ALTER TABLE PROJECT_LINK_HISTORY 	DISABLE constraint PROJECT_LINK_HIST_PROJECT_FK;
	ALTER TABLE JUNCTION_POINT 			DISABLE constraint FK_JP_ROADWAY_POINT_ID;


DECLARE
	ID_JUNCTION_POINT TABLE_OF_NUM_TYPE;
	ID_CALIBRATION_POINT TABLE_OF_NUM_TYPE;
	ID_ROADWAY TABLE_OF_NUM_TYPE;
	ID_ROADWAY_POINT TABLE_OF_NUM_TYPE;
	ID_NODE_POINT TABLE_OF_NUM_TYPE;
	ID_ROAD_NAME TABLE_OF_NUM_TYPE;
	ID_LINK TABLE_OF_NUM_TYPE;
	ID_JUNCTION TABLE_OF_NUM_TYPE;
	ID_LINEAR_LOCATION TABLE_OF_NUM_TYPE;
	ID_LINEAR_LOCATION_INSERT TABLE_OF_NUM_TYPE;
	ID_NODE TABLE_OF_NUM_TYPE;
	ID_NODE_INSERT TABLE_OF_NUM_TYPE;
	ID_PROJECT_LINK_HISTORY TABLE_OF_NUM_TYPE;
	ID_PROJECT_LINK_HISTORY_INSERT TABLE_OF_NUM_TYPE;

BEGIN
	DELETE FROM PUBLISHED_ROADWAY;
	DELETE FROM ROAD_NETWORK_ERROR;
	DELETE FROM ROADWAY_CHANGES;
	DELETE FROM ROADWAY_CHANGES_LINK;
	DELETE FROM PROJECT_LINK;
	DELETE FROM PROJECT_LINK_NAME;
	DELETE FROM PROJECT_RESERVED_ROAD_PART;
	DELETE FROM PROJECT;

	SELECT id BULK COLLECT INTO ID_JUNCTION_POINT FROM ( 
		select * from JUNCTION_POINT minus select * from JUNCTION_POINT_before_5_129);
	
	-- Delete differences from JUNCTION_POINT compared to backup table
	DELETE FROM JUNCTION_POINT WHERE id IN (SELECT * FROM TABLE (ID_JUNCTION_POINT));	
	INSERT INTO JUNCTION_POINT select * from JUNCTION_POINT_before_5_129 minus select * from JUNCTION_POINT;

	SELECT id BULK COLLECT INTO ID_CALIBRATION_POINT FROM ( 
		select * from CALIBRATION_POINT minus select * from CALIBRATION_POINT_before_5_129);
	DELETE FROM CALIBRATION_POINT WHERE id IN (SELECT * FROM TABLE (ID_CALIBRATION_POINT));
	INSERT INTO CALIBRATION_POINT select * from CALIBRATION_POINT_before_5_129 minus select * from CALIBRATION_POINT;

	SELECT id BULK COLLECT INTO ID_NODE_POINT FROM ( 
		select * from NODE_POINT minus select * from NODE_POINT_before_5_129);
	DELETE FROM NODE_POINT WHERE id IN (SELECT * FROM TABLE (ID_NODE_POINT));
	INSERT INTO NODE_POINT select * from NODE_POINT_before_5_129 minus select * from NODE_POINT;
	
	SELECT id BULK COLLECT INTO ID_ROAD_NAME FROM ( 
		select * from ROAD_NAME minus select * from ROAD_NAME_before_5_129);
	DELETE FROM ROAD_NAME WHERE id IN (SELECT * FROM TABLE (ID_ROAD_NAME));
	INSERT INTO ROAD_NAME select * from ROAD_NAME_before_5_129 minus select * from ROAD_NAME;
	
	SELECT id BULK COLLECT INTO ID_ROADWAY FROM ( 
		select * from roadway minus select * from roadway_before_5_129);
	DELETE FROM roadway WHERE id IN (SELECT * FROM TABLE (ID_ROADWAY));
	INSERT INTO roadway select * from roadway_before_5_129 minus select * from roadway;
	
	SELECT id BULK COLLECT INTO ID_ROADWAY_POINT FROM ( 
		select * from ROADWAY_POINT minus select * from ROADWAY_POINT_before_5_129);
	DELETE FROM ROADWAY_POINT WHERE id IN (SELECT * FROM TABLE (ID_ROADWAY_POINT));
	INSERT INTO ROADWAY_POINT select * from ROADWAY_POINT_before_5_129 minus select * from ROADWAY_POINT;

	SELECT id BULK COLLECT INTO ID_LINEAR_LOCATION FROM ( 
		select ID,ROADWAY_NUMBER,ORDER_NUMBER,LINK_ID,START_MEASURE,END_MEASURE,SIDE,VALID_FROM,VALID_TO,CREATED_BY,CREATED_TIME 
		FROM LINEAR_LOCATION minus
		select ID,ROADWAY_NUMBER,ORDER_NUMBER,LINK_ID,START_MEASURE,END_MEASURE,SIDE,VALID_FROM,VALID_TO,CREATED_BY,CREATED_TIME
		from LINEAR_LOCATION_before_5_129);
	SELECT id BULK COLLECT INTO ID_LINEAR_LOCATION_INSERT FROM ( 
		select ID,ROADWAY_NUMBER,ORDER_NUMBER,LINK_ID,START_MEASURE,END_MEASURE,SIDE,VALID_FROM,VALID_TO,CREATED_BY,CREATED_TIME 
		FROM LINEAR_LOCATION_before_5_129 minus
		select ID,ROADWAY_NUMBER,ORDER_NUMBER,LINK_ID,START_MEASURE,END_MEASURE,SIDE,VALID_FROM,VALID_TO,CREATED_BY,CREATED_TIME
		from LINEAR_LOCATION);
	DELETE FROM LINEAR_LOCATION WHERE id IN (SELECT * FROM TABLE (ID_LINEAR_LOCATION));
	INSERT INTO LINEAR_LOCATION SELECT * FROM LINEAR_LOCATION_before_5_129 WHERE id IN (SELECT * FROM TABLE (ID_LINEAR_LOCATION_INSERT));

	SELECT id BULK COLLECT INTO ID_LINK FROM ( 
		select * from LINK minus select * from LINK_before_5_129);
	DELETE FROM LINK WHERE id IN (SELECT * FROM TABLE (ID_LINK));
	INSERT INTO LINK select * from LINK_before_5_129 minus select * from LINK;

	SELECT id BULK COLLECT INTO ID_NODE FROM ( 
		select ID,NODE_NUMBER,NAME,"TYPE",START_DATE,END_DATE,VALID_TO,CREATED_BY,CREATED_TIME,VALID_FROM,PUBLISHED_TIME,EDITOR,REGISTRATION_DATE 
		FROM NODE minus
		select ID,NODE_NUMBER,NAME,"TYPE",START_DATE,END_DATE,VALID_TO,CREATED_BY,CREATED_TIME,VALID_FROM,PUBLISHED_TIME,EDITOR,REGISTRATION_DATE 
		FROM NODE_before_5_129);
	SELECT id BULK COLLECT INTO ID_NODE_INSERT FROM ( 
		select ID,NODE_NUMBER,NAME,"TYPE",START_DATE,END_DATE,VALID_TO,CREATED_BY,CREATED_TIME,VALID_FROM,PUBLISHED_TIME,EDITOR,REGISTRATION_DATE 
		FROM NODE_before_5_129 minus
		select ID,NODE_NUMBER,NAME,"TYPE",START_DATE,END_DATE,VALID_TO,CREATED_BY,CREATED_TIME,VALID_FROM,PUBLISHED_TIME,EDITOR,REGISTRATION_DATE 
		FROM NODE);
	
	DELETE FROM NODE WHERE id IN (SELECT * FROM TABLE (ID_NODE));
	INSERT INTO NODE SELECT * FROM NODE_before_5_129 WHERE id IN (SELECT * FROM TABLE (ID_NODE));

	SELECT id BULK COLLECT INTO ID_PROJECT_LINK_HISTORY FROM (
		select ID,PROJECT_ID,TRACK,DISCONTINUITY_TYPE,ROAD_NUMBER,ROAD_PART_NUMBER,START_ADDR_M,END_ADDR_M,CREATED_BY,MODIFIED_BY,CREATED_DATE,MODIFIED_DATE,STATUS,ROAD_TYPE,ROADWAY_ID,LINEAR_LOCATION_ID,CONNECTED_LINK_ID,ELY,REVERSED,SIDE,START_MEASURE,END_MEASURE,LINK_ID,ADJUSTED_TIMESTAMP,LINK_SOURCE,ORIGINAL_START_ADDR_M,ORIGINAL_END_ADDR_M,ROADWAY_NUMBER,START_CALIBRATION_POINT,END_CALIBRATION_POINT,ORIG_START_CALIBRATION_POINT,ORIG_END_CALIBRATION_POINT 
		from PROJECT_LINK_HISTORY minus
		select ID,PROJECT_ID,TRACK,DISCONTINUITY_TYPE,ROAD_NUMBER,ROAD_PART_NUMBER,START_ADDR_M,END_ADDR_M,CREATED_BY,MODIFIED_BY,CREATED_DATE,MODIFIED_DATE,STATUS,ROAD_TYPE,ROADWAY_ID,LINEAR_LOCATION_ID,CONNECTED_LINK_ID,ELY,REVERSED,SIDE,START_MEASURE,END_MEASURE,LINK_ID,ADJUSTED_TIMESTAMP,LINK_SOURCE,ORIGINAL_START_ADDR_M,ORIGINAL_END_ADDR_M,ROADWAY_NUMBER,START_CALIBRATION_POINT,END_CALIBRATION_POINT,ORIG_START_CALIBRATION_POINT,ORIG_END_CALIBRATION_POINT 
		from PROJECT_LINK_HISTORY_bf_5_129);
		
	SELECT id BULK COLLECT INTO ID_PROJECT_LINK_HISTORY_INSERT FROM (
		SELECT ID,PROJECT_ID,TRACK,DISCONTINUITY_TYPE,ROAD_NUMBER,ROAD_PART_NUMBER,START_ADDR_M,END_ADDR_M,CREATED_BY,MODIFIED_BY,CREATED_DATE,MODIFIED_DATE,STATUS,ROAD_TYPE,ROADWAY_ID,LINEAR_LOCATION_ID,CONNECTED_LINK_ID,ELY,REVERSED,SIDE,START_MEASURE,END_MEASURE,LINK_ID,ADJUSTED_TIMESTAMP,LINK_SOURCE,ORIGINAL_START_ADDR_M,ORIGINAL_END_ADDR_M,ROADWAY_NUMBER,START_CALIBRATION_POINT,END_CALIBRATION_POINT,ORIG_START_CALIBRATION_POINT,ORIG_END_CALIBRATION_POINT
		from PROJECT_LINK_HISTORY_bf_5_129 minus 
		SELECT ID,PROJECT_ID,TRACK,DISCONTINUITY_TYPE,ROAD_NUMBER,ROAD_PART_NUMBER,START_ADDR_M,END_ADDR_M,CREATED_BY,MODIFIED_BY,CREATED_DATE,MODIFIED_DATE,STATUS,ROAD_TYPE,ROADWAY_ID,LINEAR_LOCATION_ID,CONNECTED_LINK_ID,ELY,REVERSED,SIDE,START_MEASURE,END_MEASURE,LINK_ID,ADJUSTED_TIMESTAMP,LINK_SOURCE,ORIGINAL_START_ADDR_M,ORIGINAL_END_ADDR_M,ROADWAY_NUMBER,START_CALIBRATION_POINT,END_CALIBRATION_POINT,ORIG_START_CALIBRATION_POINT,ORIG_END_CALIBRATION_POINT
	 	from PROJECT_LINK_HISTORY);

	SELECT id BULK COLLECT INTO ID_JUNCTION FROM ( 
		select * from JUNCTION minus select * from JUNCTION_before_5_129);
	DELETE FROM JUNCTION WHERE id IN (SELECT * FROM TABLE (ID_JUNCTION));
	INSERT INTO JUNCTION select * from JUNCTION_before_5_129 minus select * from JUNCTION;

	DELETE FROM PROJECT_LINK_HISTORY WHERE id IN (SELECT * FROM TABLE (ID_PROJECT_LINK_HISTORY));
	INSERT INTO PROJECT_LINK_HISTORY SELECT * FROM PROJECT_LINK_HISTORY_bf_5_129 WHERE id IN (SELECT * FROM TABLE (ID_PROJECT_LINK_HISTORY_INSERT));
--	
	INSERT INTO PROJECT select * FROM PROJECT_bak;
	INSERT INTO PROJECT_RESERVED_ROAD_PART select * FROM PROJECT_RESERVED_ROAD_PART_bak;
	INSERT INTO PROJECT_LINK_NAME select * FROM PROJECT_LINK_NAME_bak;
	INSERT INTO PROJECT_LINK select * FROM PROJECT_LINK_bak;
	INSERT INTO ROADWAY_CHANGES_LINK select * FROM ROADWAY_CHANGES_LINK_bak;
	INSERT INTO ROADWAY_CHANGES  select * FROM ROADWAY_CHANGES_bak;

 COMMIT;
END;

ALTER TABLE JUNCTION_POINT 			ENABLE constraint JUNCTION_POINT_FK1;
ALTER TABLE NODE_POINT 				ENABLE constraint FK_NP_ROADWAY_POINT_ID;
ALTER TABLE CALIBRATION_POINT 		ENABLE constraint CP_ROADWAY_POINT_FK;
ALTER TABLE PROJECT_LINK_HISTORY 	ENABLE constraint PROJECT_LINK_HIST_PROJECT_FK;
ALTER TABLE JUNCTION_POINT 			ENABLE constraint FK_JP_ROADWAY_POINT_ID;

